### ISSUE TITLE
on* attribute being set using setAttribute

### ISSUE THREAD

**Issue by chatziko** [rpl/fennec-addon-preferences-workaround#1]
Thanks for this workaround!

I just submitted an addon using the workaround, the reviewer said:

> Please note the following for the next update:
> 1) on\* attribute being set using setAttribute
> To prevent vulnerabilities, event handlers (like 'onclick' and 'onhover') should always be defined using addEventListener.

The guilty code:

```
node_modules/fennec-addon-preferences-workaround/index.js

button.setAttribute('label', label);
button.setAttribute('oncommand', "Services.obs.notifyObservers(null, '" +
                                  id + "-cmdPressed', '" + name + "');");

else if (type === 'boolint') {
  setting.setAttribute('on', on);
  setting.setAttribute('off', off);
```

**Comment by rpl** [comment]
@chatziko Thanks for reporting this, in #2 I merged a couple of fixes and tweaks from the patch for mozilla-central (to fix the issue in the addon-sdk itself) and fixed this module as requested in the AMO review (by using addEventListener to hook the command event handler to the button).

Let me know if the updated version works for you (and if now it passes the AMO review).

**Comment by chatziko** [comment]
The new version works fine, thanks.

I haven't sent my addon for a new review, but it should be ok.
I'll close the issue for now, and re-open if I get a new review comment.
